primary-solution = "full"
check-type = "builtin"
name = "a-plus-b"
title = "P == NP?" # Clickbait :)
random-seed = "f22ab682947f4450433f21e0dfe9ddf60194610e8dc704d809c5d2237e9b0e60"
valuer = "icpc"

[builtin-check]
name = "cmp-tokens"

[[tests]]
map = "1..3"
testgen = "main"

[[tests]]
map = "4..5"
files = "{:0>1}.txt"

[[tests]]
map = "6..20"
testgen = "random"