check-type = "custom"
name = "array-sum"
title = "Finding Maximal Flow in Highly Parallel Networks"
random-seed = "2024f9ff0d28cf6321176054da58ac3fee52406b5b9a82a7c4142a74815ae779"
valuer = "icpc"

[custom-check]
pass-correct = false

[[tests]]
map = "1..2"
files = "{:0>1}.txt"

[[tests]]
map = "3..20"
testgen = "main"
