[package]
name = "soft"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.3.5"
serde_json = "1.0.44"
serde = { version = "1.0.104", features = ["derive"] }
anyhow = "1.0.25"
util = {path = "../util"}
toml = "0.5.5"
copy-ln = { git = "https://github.com/mikailbag/copy-ln", branch = "master" }
tempfile = "3.1.0"
tera = "0.11.20"
error-chain = "0.12.1"  # used inderectly to render tera error into string 