[package]
name = "ppc"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = """
PPC is tool for prepararing problems and contests
"""

[dependencies]
structopt = "0.3.7"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5.5"
snafu = "0.6.2"
glob = "0.3.0"
libc = "0.2.66"
pom = {path = "../pom"}
serde_json = "1.0.44"
getrandom = "0.1.14"
hex = "0.4.0"
formatf = { git = "https://github.com/mikailbag/formatf" }
roxmltree = "0.9.0"
