[package]
name = "cfg"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
toml = "0.5.6"
pom = {path = "../pom"}
serde_json = "1.0.44"
