version: '3.7'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: root
  init-db:
    image: jjs:latest
    command:
      - "jjs-setup"
      - "--install-dir=/opt/jjs"
      - "--data-dir=/var/lib/jjs"
      - "--setup-config"
      - "--sample-contest"
      - "--db-url=postgres://db:5432/jjs"
      - "--toolchains"
      - "--touch=/var/lib/jjs/done.txt"
    depends_on:
      - db
    environment:
      RUST_LOG: debug
      JJS_WAIT: tcp://db:5432
    volumes:
      - type: 'volume'
        source: jjs_data
        target: /var/lib/jjs
    security_opt:
      - seccomp=unconfined
  frontend:
    image: jjs:latest
    environment:
      DATABASE_URL: postgres://db:5432/jjs
      JJS_SYSROOT: /var/lib/jjs
      JJS_PATH: /opt/jjs
      JJS_WAIT: file:///var/lib/jjs/done.txt
      JJS_HOST: "0.0.0.0"
      RUST_LOG: info,frontend=debug,util=debug,frontend_engine=debug
      JJS_SELF_ADDR: frontend
    command: 
      - jjs-frontend
    depends_on:
      - db
      - init-db
    volumes:
      - type: 'volume'
        source: jjs_data
        target: /var/lib/jjs
    ports:
      - "1779:1779"
  invoker:
    image: jjs:latest
    privileged: true
    command: 
      - /bin/jjs-invoker
    environment:
      DATABASE_URL: postgres://db:5432/jjs
      JJS_SYSROOT: /var/lib/jjs
      JJS_PATH: /opt/jjs
      JJS_WAIT: file:///var/lib/jjs/done.txt
      RUST_LOG: info,invoker=debug,util=debug,svaluer=debug
      RUST_BACKTRACE: full
      RUST_LIB_BACKTRACE: 1
    command: 
      - jjs-invoker
    depends_on:
      - db
      - init-db
    volumes:
      - type: 'volume'
        source: jjs_data
        target: /var/lib/jjs
volumes:
  jjs_data:

