merge_imports = true
force_explicit_abi = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
edition = "2018"
merge_derives = true
newline_style = "Unix"
report_fixme = "Unnumbered"
unstable_features = true
version = "Two"
