[package]
name = "util"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libsystemd = "0.1.0"
log = "0.4.8"
atty = "0.2.13"
slog = "2.5.2"
slog-term = "2.4.1"
slog-envlogger = "2.2.0"
slog-scope = "4.2.0"
slog-stdlog = "4.0.0"
url = "2.1.0"
