[package]
name = "cli"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = "JJS CLI client"

[dependencies]
frontend-api = {path = "../frontend-api"}
structopt = "0.3.6"
base64 = "0.11.0"
slog = "2.5.2"
serde_json = "1.0.44"
graphql_client = "0.8.0"
serde = "1.0.104"
slog-envlogger = "2.2.0"
slog-stdlog = "4.0.0"
slog-term = "2.4.2"
slog-scope = "4.3.0"
