[package]
name = "setup"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = """
Simple utility to setup JJS on current host
"""

[dependencies]
backtrace = "0.3.40"
fs_extra = "1.1.0"
structopt = "0.3.7"
util = {path = "../util"}
log = "0.4.8"
url = "2.1.1"
anyhow = "1.0.26"
