[package]
name = "userlist"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.3.7"
snafu = "0.6.0"
frontend-api = {path = "../frontend-api"}
base64 = "0.11.0"
pest = "2.1.2"
pest_derive = "2.1.0"
graphql_client = "0.8.0"
reqwest = "0.10.0"
serde = { version = "1.0.104", features = ["derive"] }
uuid = "0.7.4"
