[package]
name = "userlist"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.3.5"
snafu = "0.5.0"
frontend-api = {path = "../frontend-api"}
base64 = "0.10.1"
pest = "2.1.2"
pest_derive = "2.1.0"
graphql_client = "0.8.0"
reqwest = "0.9.22"
serde = { version = "1.0.103", features = ["derive"] }
uuid = "0.7.4"
