[package]
name = "frontend-engine"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
digest = "0.8.1"
db = {path = "../db"}
rand = "0.7.2"
slog = "2.5.2"
juniper = "0.14.0"
uuid = "0.7.4"
rocket = "0.4.2"
serde = "1.0.101"
sha3 = "0.8.2"
rand_chacha = "0.2.1"
cfg = {path = "../cfg"}
base64 = "0.10.1"
constant_time_eq = "0.1.4"
libc = "0.2.62"
serde_json = "1.0.40"
branca = "0.9.0"
juniper_rocket = "0.5.0"
backtrace = "0.3.38"
snafu = "0.5.0"
ranker = {path = "../ranker"}
util = {path = "../util"}
slog-scope = "4.1.2"

[dev-dependencies]
serde_yaml = "0.8.9"
toml = "0.5.3"
setup = {path = "../setup"}
